### ISSUE TITLE
Update readme startup

### ISSUE THREAD

**Issue by OUeasley** [dr-copper/bundleup#1]
Following steps from here:

Then be sure to activate the corresponding environment:

$ . venv/bin/activate
The shell will then update to show the name of the activated environment. After activation, use the following command to install Flask via pip:

$ pip install Flask
After the installation is complete, use the flask command to run the application:

$ flask run
If installed and setup correctly, your terminal should show the app running:

 * Running on http://127.0.0.1:5000/

But when I do this nothing happens it just fails off the bat.

This doesn't seem correct, but perhaps I'm doing something incorrectly. Here is the error:

```
Error: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
❯ flask run bundleup.py
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.
```

**Comment by dr-copper** [comment]
My apologies in the delay, the updated program has been tested and should be working with any rework: 

- Index.html was not located in the templates folder **(fixed)** 
- Main function was erroneously in the middle of the script **(fixed)** 
- Included app.secret_key as to sign cookies as a preventative measure against tampering **(added)** 
- Created a function called create_upload_folder() which creates the upload folder on start if it's not there **(fixed)** 
- Changed the app.config['UPLOAD_PATH'] = os.path.join(os.path.dirname(__file__), 'uploads') to add consistency **(fixed)**

Please advise if for any reason there is still a persistent issue. Thank you
